name: Build and Deploy
on:
  push:
    branches:
      - main
      - feature/add-cicd

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
        working-directory: ./functions
      - name: Set Functions env
        run: echo '${{ secrets.FIREBASE_FUNCTIONS_ENV }}' > ./functions/.env
      - name: Set Service Account
        run: |
          mkdir ./functions/key/
          echo '${{ secrets.SERVICE_ACCOUNT }}' > ./functions/key/service-account.json
      - name: Build Functions
        run: yarn build
        working-directory: ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
