name: Build and Deploy
on:
  push:
    branches:
      - main
      - feature/add-cicd

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
        working-directory: ./functions
      - name: Build Functions
        run: yarn build
        working-directory: ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
